"""Backfill Qdrant embeddings for the already-loaded seed nodes (one-off).

The Libro IV seed graph was loaded with MERLT_SKIP_EMBEDDINGS=true (e5-large on
docker CPU is slow), so the Qdrant collection is near-empty and semantic retrieval
returns nothing. The main loader (`load_seed_libro_iv`) short-circuits on a
non-empty graph (>100 nodes) BEFORE the embedding step, so embeddings can't be
generated by re-running it — this calls the embedding step directly.

Reuses `load_seed_libro_iv._generate_and_upsert_embeddings` so the chunking /
text-preference / Qdrant upsert logic stays in one place.

Run (detached, hours on CPU) inside a container that has the model + Qdrant:
    docker exec -d visualex-merlt-worker sh -c \
      'python -m merlt.scripts.backfill_embeddings > /tmp/backfill-embeddings.log 2>&1'
"""

from __future__ import annotations

import asyncio
import json
import os
from pathlib import Path

import structlog

from merlt.scripts.load_seed_libro_iv import (
    _generate_and_upsert_embeddings,
    SEED_GRAPH_JSON,
)

log = structlog.get_logger()


async def _run() -> None:
    graph_path = Path(os.getenv("MERLT_SEED_GRAPH_PATH") or SEED_GRAPH_JSON)
    data = json.loads(graph_path.read_text(encoding="utf-8"))
    nodes = data.get("nodes", [])
    collection = os.getenv("MERLT_SEED_COLLECTION", "merl_t_legal_chunks")

    from qdrant_client import QdrantClient
    from merlt.storage.vectors.embeddings import EmbeddingService

    if os.getenv("QDRANT_URL"):
        qdrant = QdrantClient(url=os.getenv("QDRANT_URL"))
    else:
        qdrant = QdrantClient(
            host=os.getenv("QDRANT_HOST", "localhost"),
            port=int(os.getenv("QDRANT_PORT", "6333")),
        )
    embeddings = EmbeddingService.get_instance()

    log.info("backfill_embeddings.starting", nodes=len(nodes), collection=collection)
    count, _ = await _generate_and_upsert_embeddings(nodes, embeddings, qdrant, collection)
    log.info("backfill_embeddings.done", upserted=count)


if __name__ == "__main__":
    asyncio.run(_run())
