import type { Request } from 'express';
import { timingSafeEqual } from 'node:crypto';
import { sha256 } from './hash';

/**
 * The MCP server's own credential: the one confidential client. It is not in
 * `oauth_clients` (registration only ever makes public clients): its id is
 * fixed and its secret comes from the environment, generated by the setup
 * scripts. With no secret configured, nothing authenticates as it.
 */
export const MCP_CLIENT_ID = 'mcp-omnilex';

// Read at each call, not at import: the server reads its environment once at
// start in production, and tests set it before their first request.
const configuredSecret = (): string | undefined => process.env.OAUTH_MCP_CLIENT_SECRET || undefined;

const sameSecret = (given: string, expected: string): boolean =>
  // Hash both sides so the comparison is constant-time whatever the lengths.
  timingSafeEqual(Buffer.from(sha256(given), 'hex'), Buffer.from(sha256(expected), 'hex'));

/** Whether the request carries the MCP server's credential (HTTP Basic, RFC 6749 §2.3.1). */
export function isMcpClient(req: Request): boolean {
  const expected = configuredSecret();
  const header = req.headers.authorization;
  if (!expected || !header?.startsWith('Basic ')) return false;
  const decoded = Buffer.from(header.slice(6), 'base64').toString('utf8');
  const colon = decoded.indexOf(':');
  if (colon < 0) return false;
  const id = decodeURIComponent(decoded.slice(0, colon));
  const secret = decodeURIComponent(decoded.slice(colon + 1));
  return id === MCP_CLIENT_ID && sameSecret(secret, expected);
}
